import firebase from 'firebase';
import config from '../config/index';
import {
  loadUser,
  resetErrorMessage,
  validateAuthField,
  validateUserDetailsField,
  validateAnotherUserDetailsField,
  credentialsUpdate,
  loginRequest,
  logoutRequest,
  loginSuccess,
  logoutSuccess,
  loginFailure,
  logoutFailure,
  loginUser,
  logoutUser,
  openEvent,
  openEventMethod,
} from './authentication';
import {
  refreshMessages,
  sendingMessage,
  sendingName,
  sendColorAction,
  sendHistoryAction,
  sendMessageAction,
  sendChatMessage,
  sendChatName,
  connectionError,
  browserNotSupported,
  browserSupported,
  testBrowserSupport,
} from './webSockets';

firebase.initializeApp(config);

export {
  loadUser,
  resetErrorMessage,
  validateAuthField,
  validateUserDetailsField,
  validateAnotherUserDetailsField,
  credentialsUpdate,
  loginRequest,
  logoutRequest,
  loginSuccess,
  logoutSuccess,
  loginFailure,
  logoutFailure,
  loginUser,
  logoutUser,
  refreshMessages,
  sendingMessage,
  sendingName,
  sendColorAction,
  sendHistoryAction,
  sendMessageAction,
  sendChatMessage,
  sendChatName,
  openEvent,
  openEventMethod,
  connectionError,
  browserNotSupported,
  browserSupported,
  testBrowserSupport,
};
